# cfg for preprocess.py

audio_exts : ['wav','mp3','m4a','flac','aiff']

# Input data paths
metadata_path : 'data/dali.csv'
dali_subset_flist : 'data/dali_subset.json'
dali_audio_dir : '/import/c4dm-datasets/DALI_v2.0/audio'
dali_annot_dir : '/import/c4dm-datasets/DALI_v2.0/annot_tismir'

# Processed data paths
cqt_dir : 'data/cqt'
crema_dir : 'data/crema_pcp'
lvec_dir : 'data/lvec'

# Preprocessing parameters
sr_h : 22050
sr_l : 16000
hop_length : 500

# Hyperparameters
seed : 42
batch_size : 16
num_workers : 4
lr : 0.0001
n_epochs : 100
T_max : 80
gamma : 0.9
num_workers : 4
crema_threshold : null
lyr_enc_threshold : 1
norm : 0.95
embed_dim : 12

# Model parameters
SE_blocks: [1, 2, 1, 2]
freq_mask: 28
time_mask: 100
noise_std: False
